### ISSUE TITLE
Following the Getting Started guide yields a black map

### ISSUE THREAD

**Issue by msmollin** [mapzen/android#59]
Once I worked thru the compiler, import, and dependency import issues, I get a black map rendered on all devices and emulators.

I am assuming it's something todo with vector tiles not getting downloaded and handed off, because (on device at least) everything initializes correctly.

Devices test:
1+1 running 5.1.1
Nexus 7 2013 running 6.0.1

**Comment by msmollin** [comment]
N7: 
![device-2016-04-26-122851](https://cloud.githubusercontent.com/assets/1163880/14826151/9943e112-0baa-11e6-9fa0-405baeaeb35b.png)

**Comment by ecgreb** [comment]
Fixed by https://github.com/mapzen/android/commit/150dccd3c2ab3fff9b350bb5f06e42d880a5b8e5

**Comment by fedorparetsky** [comment]
I am still getting this issue. Getting a black screen, and followed 150dccd.
